---
abstract: 'CRUD for Catalyst::Model::DBIC::Schema'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CatalystX-CRUD-ModelAdapter-DBIC
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst::Model::DBIC::Schema: '0'
  CatalystX::CRUD: '0.42'
  CatalystX::CRUD::Controller::REST: '0'
  DBIx::Class: '0'
  DBIx::Class::RDBOHelpers: '0.04'
  Data::Dump: '0'
  Test::More: '0'
resources:
  repository: https://github.com/karpet/catalystx-crud-modeladapter-dbic
version: '0.15'
